name: bajajhealthapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  graphql_flutter: 1.0.0+4
  shared_preferences:
  scoped_model:
  intl:
  undraw:
  table_calendar:
  google_sign_in:
  googleapis:
  torch:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/branding/header.png
   - assets/img/dashboard/blob.png
   - assets/img/dashboard/person.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.otf
      - asset: assets/fonts/poppins/Poppins-Light.otf
      - asset: assets/fonts/poppins/Poppins-Regular.otf
      - asset: assets/fonts/poppins/Poppins-Medium.otf
      - asset: assets/fonts/poppins/Poppins-SemiBold.otf
      - asset: assets/fonts/poppins/Poppins-Bold.otf
  - family: 'PT Sans'
    fonts:
      - asset: assets/fonts/PTsans/PTC55F.ttf
      - asset: assets/fonts/PTsans/PTC75F.ttf
      - asset: assets/fonts/PTsans/PTN57F.ttf
      - asset: assets/fonts/PTsans/PTN77F.ttf
      - asset: assets/fonts/PTsans/PTS55F.ttf
      - asset: assets/fonts/PTsans/PTS56F.ttf
      - asset: assets/fonts/PTsans/PTS75F.ttf
      - asset: assets/fonts/PTsans/PTS76F.ttf
  - family: 'Raleway'
    fonts:
      - asset: assets/fonts/Raleway/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway/Raleway-Medium.ttf
      - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
      - asset: assets/fonts/Raleway/Raleway-Thin.ttf
      - asset: assets/fonts/Raleway/Raleway-Light.ttf
  - family: 'Montserrat'
    fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Regular.otf
      - asset: assets/fonts/Montserrat/Montserrat-Light.otf
      - asset: assets/fonts/Montserrat/Montserrat-SemiBold.otf
      - asset: assets/fonts/Montserrat/Montserrat-Medium.otf
      - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
      - asset: assets/fonts/Montserrat/Montserrat-Thin.otf
  - family: 'Comfortaa'
    fonts:
      - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Thin.ttf
  - family: 'Righteous'
    fonts:
      - asset: assets/fonts/Righteous/Righteous-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
